name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: 'latablerouge-theme'
      FILES_TO_INCLUDE: 'LICENSE.txt index.php includes build'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.0.0

      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Build the theme
      - name: Build theme
        run: |
          npm run build --chore=ci

      # Zip the files
      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          tar -czf "${GITHUB_SHA}".tar.gz --ignore-failed-read ${FILES_TO_INCLUDE}

      # Upload the artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-build
          path: ${{ github.sha }}.tar.gz
          retention-days: 1
