name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: theme-build

      - name: Extract tarball
        run: |
          mkdir -p theme-build
          tar -xzf *.tar.gz -C theme-build

      - name: Install Composer dependencies
        run: |
          cd theme-build
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Get runner's public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelisting the runner IP
        run: |
          curl -sm 45 -H'Authorization: cpanel ${{ secrets.O2SWITCH_LOGIN }}:${{ secrets.O2SWITCH_TOKEN }}' \
          'https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/add?address=${{ steps.ip.outputs.ipv4 }}&port=22'

      - name: Making sure the IP is whitelisted
        run: |
          curl -sm 45 -H'Authorization: cpanel ${{ secrets.O2SWITCH_LOGIN }}:${{ secrets.O2SWITCH_TOKEN }}' \
          'https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/list' | grep ${{ steps.ip.outputs.ipv4 }}

      - name: Installing the SSH Key
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa

      - name: Sending data with RSYNC
        run: |
          sleep 2
          rsync --timeout=60 -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          --exclude=".git" -av --delete theme-build/ \
          ${{ secrets.O2SWITCH_LOGIN }}@${{ secrets.O2SWITCH_SERVER }}:/home/${{ secrets.O2SWITCH_LOGIN }}/${{ secrets.SERVER_PATH}}

      - name: Cleaning SSH keys
        if: always()
        run: rm -fr ~/.ssh

      - name: Removing whitelisted IP
        run: |
          curl -sm 45 -H'Authorization: cpanel ${{ secrets.O2SWITCH_LOGIN }}:${{ secrets.O2SWITCH_TOKEN }}' \
          'https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/remove?address=${{ steps.ip.outputs.ipv4 }}&port=22&direction=in'
          curl -sm 45 -H'Authorization: cpanel ${{ secrets.O2SWITCH_LOGIN }}:${{ secrets.O2SWITCH_TOKEN }}' \
          'https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/remove?address=${{ steps.ip.outputs.ipv4 }}&port=22&direction=out'

      - name: Cleaning artifacts
        uses: geekyeggo/delete-artifact@v5
        if: always()
        with:
          name: theme-build
          failOnError: false
